#include "CommonIncludes.h"
#include "LuaAutocompleteGenerator.h"
#include "LuaSystem.h"
#include <fstream>
#include <set>
#include <sstream>
#include <string>

using namespace Unigine;

bool LuaAutocompleteGenerator::generateLSPDefinitions(const Unigine::String& output_path)
{
    LuaSystem* ls = LuaSystem::get();
    if (!ls)
        return false;
    
    sol::state& lua = ls->getState();
    
    std::vector<FunctionSignature> functions;
    std::vector<TypeDefinition> types;
    extractSignatures(lua, functions, types);
    
    std::ofstream file(output_path.get());
    if (!file.is_open())
    {
        Log::error("[Autocomplete] Failed to open file for writing: %s\n", output_path.get());
        return false;
    }
    
    // Generate LSP definition file (sumneko-lua format)
    file << "-- LSP definitions for Unigine Lua API\n";
    file << "-- Auto-generated by LuaAutocompleteGenerator\n\n";
    
    // Write type definitions
    for (const auto& type : types)
    {
        file << "---@class " << type.name << "\n";
        for (const auto& prop : type.properties)
        {
            file << "---@field " << prop << " any\n";
        }
        file << "local " << type.name << " = {}\n\n";
    }
    
    // Write function signatures
    for (const auto& func : functions)
    {
        file << "---" << func.description << "\n";
        file << "---@param ";
        for (size_t i = 0; i < func.parameters.size(); i++)
        {
            if (i > 0) file << " ";
            file << func.parameters[i];
        }
        file << "\n";
        file << "---@return " << func.return_type << "\n";
        file << "function " << func.name << "(";
        for (size_t i = 0; i < func.parameters.size(); i++)
        {
            if (i > 0) file << ", ";
            file << "param" << i;
        }
        file << ") end\n\n";
    }
    
    file.close();
    Log::message("[Autocomplete] Generated LSP definitions: %s\n", output_path.get());
    return true;
}

bool LuaAutocompleteGenerator::generateLuaStubs(const Unigine::String& output_path)
{
    LuaSystem* ls = LuaSystem::get();
    if (!ls)
        return false;
    
    sol::state& lua = ls->getState();
    
    std::vector<FunctionSignature> functions;
    std::vector<TypeDefinition> types;
    extractSignatures(lua, functions, types);
    
    std::ofstream file(output_path.get());
    if (!file.is_open())
    {
        Log::error("[Autocomplete] Failed to open file for writing: %s\n", output_path.get());
        return false;
    }
    
    file << "-- Unigine Lua API Stubs\n";
    file << "-- Auto-generated by LuaAutocompleteGenerator\n\n";
    
    // Generate type stubs
    for (const auto& type : types)
    {
        file << "---@class " << type.name << "\n";
        file << type.name << " = {}\n\n";
        
        for (const auto& method : type.methods)
        {
            file << "---" << method.description << "\n";
            file << "function " << type.name << ":" << method.name << "(";
            for (size_t i = 0; i < method.parameters.size(); i++)
            {
                if (i > 0) file << ", ";
                file << "param" << i;
            }
            file << ") end\n\n";
        }
    }
    
    // Generate global function stubs
    for (const auto& func : functions)
    {
        file << "---" << func.description << "\n";
        file << "function " << func.name << "(";
        for (size_t i = 0; i < func.parameters.size(); i++)
        {
            if (i > 0) file << ", ";
            file << "param" << i;
        }
        file << ") end\n\n";
    }
    
    file.close();
    Log::message("[Autocomplete] Generated Lua stubs: %s\n", output_path.get());
    return true;
}

bool LuaAutocompleteGenerator::generateEmmyLuaAnnotations(const Unigine::String& output_path)
{
    LuaSystem* ls = LuaSystem::get();
    if (!ls)
        return false;
    
    sol::state& lua = ls->getState();
    
    std::vector<FunctionSignature> functions;
    std::vector<TypeDefinition> types;
    extractSignatures(lua, functions, types);
    
    std::ofstream file(output_path.get());
    if (!file.is_open())
    {
        Log::error("[Autocomplete] Failed to open file for writing: %s\n", output_path.get());
        return false;
    }
    
    file << "-- EmmyLua annotations for Unigine Lua API\n";
    file << "-- Auto-generated by LuaAutocompleteGenerator\n\n";
    
    // Generate type annotations
    for (const auto& type : types)
    {
        file << "---@class " << type.name << "\n";
        for (const auto& prop : type.properties)
        {
            file << "---@field " << prop << " any\n";
        }
        file << type.name << " = {}\n\n";
    }
    
    file.close();
    Log::message("[Autocomplete] Generated EmmyLua annotations: %s\n", output_path.get());
    return true;
}

namespace
{
    bool skipGlobalKey(const std::string& key)
    {
        if (key.empty() || key[0] == '_')
            return true;
        if (key == "coroutine" || key == "package" || key == "string" || key == "table" ||
            key == "math" || key == "io" || key == "os" || key == "debug" || key == "bit")
            return true;
        return false;
    }

    void collectFromTable(sol::table& t, const std::string& prefix,
                          std::vector<FunctionSignature>& functions,
                          std::vector<TypeDefinition>& types,
                          std::set<std::string>& seen_funcs, std::set<std::string>& seen_types,
                          int depth)
    {
        const int max_depth = 2;
        if (depth > max_depth || !t.valid())
            return;

        TypeDefinition typ;
        typ.name = prefix;

        t.for_each([&](const sol::object& key, const sol::object& value) {
            if (!key.is<std::string>())
                return;
            std::string k = key.as<std::string>();
            if (skipGlobalKey(k) && depth == 0)
                return;

            std::string full = prefix.empty() ? k : (prefix + "." + k);

            if (value.is<sol::function>())
            {
                if (seen_funcs.insert(full).second)
                {
                    FunctionSignature fs;
                    fs.name = full;
                    fs.return_type = "any";
                    fs.parameters = {};
                    fs.description = "Lua function: " + full;
                    functions.push_back(fs);
                }
                typ.methods.push_back({k, "any", {}, "Method"});
            }
            else if (value.is<sol::table>())
            {
                sol::table nested = value.as<sol::table>();
                if (depth < max_depth)
                {
                    collectFromTable(nested, full, functions, types, seen_funcs, seen_types, depth + 1);
                }
            }
        });

        if (!typ.name.empty() && !typ.methods.empty() && seen_types.insert(typ.name).second)
            types.push_back(typ);
    }
}

void LuaAutocompleteGenerator::extractSignatures(sol::state& lua,
                                                 std::vector<FunctionSignature>& functions,
                                                 std::vector<TypeDefinition>& types)
{
    functions.clear();
    types.clear();

    std::set<std::string> seen_funcs, seen_types;

    sol::table globals = lua["_G"];
    if (globals.valid())
        collectFromTable(globals, "", functions, types, seen_funcs, seen_types, 0);

    if (functions.empty() && types.empty())
    {
        TypeDefinition node_type;
        node_type.name = "NodePtr";
        node_type.methods.push_back({"getWorldPosition", "Vec3", {}, "Get world position"});
        node_type.methods.push_back({"setWorldPosition", "void", {"Vec3"}, "Set world position"});
        node_type.methods.push_back({"getName", "string", {}, "Get node name"});
        types.push_back(node_type);
        functions.push_back({"Log.message", "void", {"string"}, "Log a message"});
        functions.push_back({"Log.error", "void", {"string"}, "Log an error"});
        functions.push_back({"Vec3.new", "Vec3", {"number", "number", "number"}, "Create a Vec3"});
    }
}
